#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Goto Shingo
# SPDX-Lisence-Identifer: BSD-3-Clause

import sys
import unicodedata
import re
from collections import Counter

print("Put some sentence.\nPress Ctrl+D twice, for starting analizing")
text = sys.stdin.read()
text = unicodedata.normalize('NFKC', text)

letter_counts = {}
space = 0
others = 0
total = 0
rate = 0

for char in text:
    if re.findall(r'[A-Za-z]',char):
        if char in letter_counts:
            letter_counts[char] += 1
            total += 1
        else:
            letter_counts[char] = 1
            total += 1
    elif char == ' ':
        space += 1
    else:
        others += 1

sorted_letters = sorted(letter_counts.items(), key = lambda item: item[1], reverse = True)

for letter, count in sorted_letters:
    rate = (count / total)*100
    print(f"\n{letter}: {count}    :{rate:.2f}%", end = ' ')
print(f"\nspace:{space}")
print(f"others:{others}")
print(f"total:{total}")

