#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Goto Shingo
# SPDX-Lisence-Identifer: BSD-3-Clause

import sys

def count():
    total = 0
    text = input("input an English sentence:")

    for char in text:
        if not char.isspace():
            total += 1
    print(f"{total}")

count()
