#!/bin/bash
# SPDX-FileCopyrightText: 2024 Goto Shingo
# SPDX-License-Identifier: BSD-3-Clause

ng() {
    echo "${1}行目が違うよ"
    res=1
}

res=0


output=$(echo "Helloh wor1dっ!" | ./task1)

[ "$(echo "$output" | echo "$letter" = '[A-Z]')" ] || ng "$LINENO"
[ "$(echo "$output" | echo "$space" = 1 )" ] || ng "$LINENO"
[ "$(echo "$output" | echo "$others" = 4)" ] || ng "$LINENO"
[ "$(echo "$output" | echo "$total" = 10)" ] || ng "$LINENO"

[ "${res}" = 0 ] && echo OK


exit $res
