#!/bin/bash
# SPDX-License=Identifier: BSD-3-Clause

ng() {
    echo "${1}行目が違うよ"
    res=1
}

res=0


output=$(echo "Helloh wor1dっ!" | ./task1)

echo "$output" | grep -q '[A-Z]' && ng "$LINENO"

[ "$res" = 0 ] && echo OK


exit $res
