#!/bin/bash
# SPDX-FileCopyrightText: 2024 Goto Shingo
# SPDX-License-Identifier: BSD-3-Clause

ng() {
    echo "${1}行目が違うよ"
    res=1
}

res=0

output=$(echo Hello w0r1d | ./counter)

if [ "$output" -lt 10 ]; then
    ng "$LINENO"
    echo "less counted" 
fi

if [ "$output" -gt 10 ]; then
    ng "$LINENO"
    echo "over counted"
fi

[ "$res" = 0 ] && echo OK

exit $res
